Label Encoder

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [14]:
data = pd.read_csv('/Users/furkhanansari/Desktop/Data Science/DataSets/iris (1).csv')
data.head()

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [15]:
data.drop(columns = ['Unnamed: 0'],axis =1 , inplace = True)

In [16]:
data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
# Changes dose not effect the "data" dataframe
data1 = data.copy()

In [18]:
labelencoder = LabelEncoder()
data1.iloc[:,-1] = labelencoder.fit_transform(data1.iloc[:,-1])

In [21]:
data1

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

One Hot Encoder
two methos 
    one sklearn 
    second pandas

Using sklearn

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
data2 = data

In [27]:
data2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [30]:
# creating instances of one-hot-encoder
enc = OneHotEncoder(handle_unknown = 'ignore')

In [31]:
# passing the bridge-types-cat column (label encoded values of biridge_types)
enc_df = pd.DataFrame(enc.fit_transform(data2[['Species']]).toarray())

In [32]:
enc_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [33]:
# merge wiht the main df
data_final = data2.iloc[:,0:4].join(enc_df)
data_final

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    0    1    2
0             5.1          3.5           1.4          0.2  1.0  0.0  0.0
1             4.9          3.0           1.4          0.2  1.0  0.0  0.0
2             4.7          3.2           1.3          0.2  1.0  0.0  0.0
3             4.6          3.1           1.5          0.2  1.0  0.0  0.0
4             5.0          3.6           1.4          0.2  1.0  0.0  0.0
..            ...          ...           ...          ...  ...  ...  ...
145           6.7          3.0           5.2          2.3  0.0  0.0  1.0
146           6.3          2.5           5.0          1.9  0.0  0.0  1.0
147           6.5          3.0           5.2          2.0  0.0  0.0  1.0
148           6.2          3.4           5.4          2.3  0.0  0.0  1.0
149           5.9          3.0           5.1          1.8  0.0  0.0  1.0

[150 rows x 7 columns]

using the pandas

In [34]:
import pandas as pd

In [35]:
data3 = data

In [36]:
data_encoded = pd.get_dummies(data3)

In [37]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,False,True
146,6.3,2.5,5.0,1.9,False,False,True
147,6.5,3.0,5.2,2.0,False,False,True
148,6.2,3.4,5.4,2.3,False,False,True
149,5.9,3.0,5.1,1.8,False,False,True

Isolation forest

In [78]:
from sklearn.ensemble import IsolationForest

In [79]:
df = data

In [80]:
data_encoded = pd.get_dummies(df)
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,False,True
146,6.3,2.5,5.0,1.9,False,False,True
147,6.5,3.0,5.2,2.0,False,False,True
148,6.2,3.4,5.4,2.3,False,False,True
149,5.9,3.0,5.1,1.8,False,False,True

In [81]:
# training the model
clf = IsolationForest(random_state =10 , contamination = .01)
clf.fit(data_encoded)

IsolationForest(contamination=0.01, random_state=10)

In [82]:
# prediction 
y_pred_outliers = clf.predict(data_encoded)

In [83]:
# -1 for outliers and 1 for normal data point
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [84]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,False,True
146,6.3,2.5,5.0,1.9,False,False,True
147,6.5,3.0,5.2,2.0,False,False,True
148,6.2,3.4,5.4,2.3,False,False,True
149,5.9,3.0,5.1,1.8,False,False,True

In [85]:
# lets add some outliers and check weather the model is predicting the outliers or not
data_encoded.loc[151] = [20,40,30,50,1,0,0]

In [86]:
# training the model
clf = IsolationForest(random_state =10 , contamination = .10)
clf.fit(data_encoded)

IsolationForest(contamination=0.1, random_state=10)

In [87]:
# prediction 
y_pred_outliers = clf.predict(data_encoded)

In [88]:
# -1 for outliers and 1 for normal data point
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [89]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1
151,20.0,40.0,30.0,50.0,1,0,0

In [90]:
data_encoded['scores'] = clf.decision_function(data_encoded)

In [91]:
data_encoded['anomaly'] = clf.predict(data_encoded.iloc[:,0:7])

In [92]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
0,5.1,3.5,1.4,0.2,1,0,0,0.139220,1
1,4.9,3.0,1.4,0.2,1,0,0,0.121298,1
2,4.7,3.2,1.3,0.2,1,0,0,0.111054,1
3,4.6,3.1,1.5,0.2,1,0,0,0.119649,1
4,5.0,3.6,1.4,0.2,1,0,0,0.136000,1
...,...,...,...,...,...,...,...,...,...
146,6.3,2.5,5.0,1.9,0,0,1,0.072156,1
147,6.5,3.0,5.2,2.0,0,0,1,0.116631,1
148,6.2,3.4,5.4,2.3,0,0,1,0.060599,1
149,5.9,3.0,5.1,1.8,0,0,1,0.093843,1
151,20.0,40.0,30.0,50.0,1,0,0,-0.349947,-1

In [93]:
data_encoded[data_encoded['anomaly']==-1]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
13,4.3,3.0,1.1,0.1,1,0,0,-0.030656,-1
14,5.8,4.0,1.2,0.2,1,0,0,-0.011342,-1
15,5.7,4.4,1.5,0.4,1,0,0,-0.008138,-1
41,4.5,2.3,1.3,0.3,1,0,0,-0.031366,-1
57,4.9,2.4,3.3,1.0,0,1,0,-0.010862,-1
60,5.0,2.0,3.5,1.0,0,1,0,-0.048754,-1
70,5.9,3.2,4.8,1.8,0,1,0,-0.009004,-1
98,5.1,2.5,3.0,1.1,0,1,0,-0.026801,-1
106,4.9,2.5,4.5,1.7,0,0,1,-0.070981,-1
109,7.2,3.6,6.1,2.5,0,0,1,-0.016883,-1
117,7.7,3.8,6.7,2.2,0,0,1,-0.044210,-1
118,7.7,2.6,6.9,2.3,0,0,1,-0.053455,-1
119,6.0,2.2,5.0,1.5,0,0,1,-0.024985,-1
131,7.9,3.8,6.4,2.0,0,0,1,-0.049428,-1
151,20.0,40.0,30.0,50.0,1,0,0,-0.349947,-1

PPS SCORE

In [95]:
#  installing the package
!pip install ppscore

Collecting ppscore
  Downloading ppscore-1.3.1.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from ppscore) (2.3.3)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /opt/anaconda3/lib/python3.13/site-packages (from ppscore) (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.5.2)
Requirement already satisfied: narwhals>=2.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.0->ppscore) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.0->ppscore) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.0->ppscore) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ppscore) (1.17.0)
Building wheels for collected packages: ppscore
  Building wheel for ppscore (pyproject.toml) ... done
  Created wheel for ppscore: filename=ppscore-1.3.1-py2.py3-none-any.whl size=13225 sha256=27bfed2a9b37548677a62979b933ba94de7b69a099224c3e8fc4b7b19e61c378
  Stored in directory: /Users/furkhanansari/Library/Caches/pip/wheels/b4/95/1f/bfb3b7b3845232909c01caa738277f86d0148164d3a617ad42
Successfully built ppscore
Installing collected packages: ppscore
Successfully installed ppscore-1.3.1

In [96]:
import ppscore as pps

In [99]:
# pps.score(df , 'feature_columns(x)' , 'target_column(y)')    syntax
pps.score(data , "Sepal.Length" , "Petal.Length")

{'x': 'Sepal.Length',
 'y': 'Petal.Length',
 'ppscore': np.float64(0.550422595049248),
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 1.4886666666666668,
 'model_score': np.float64(0.6692708968366863),
 'model': DecisionTreeRegressor()}

In [102]:
# calculate the whole pps matrix for complete dataset
pps_matrix = pps.matrix(data)
pps_matrix

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,Sepal.Length,Sepal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,Sepal.Length,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.364704,DecisionTreeRegressor()
2,Sepal.Length,Petal.Length,0.550423,regression,True,mean absolute error,1.488667,0.669271,DecisionTreeRegressor()
3,Sepal.Length,Petal.Width,0.431739,regression,True,mean absolute error,0.644667,0.366339,DecisionTreeRegressor()
4,Sepal.Length,Species,0.471649,classification,True,weighted F1,0.353333,0.658333,DecisionTreeClassifier()
5,Sepal.Width,Sepal.Length,0.006966,regression,True,mean absolute error,0.684667,0.679897,DecisionTreeRegressor()
6,Sepal.Width,Sepal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
7,Sepal.Width,Petal.Length,0.172375,regression,True,mean absolute error,1.488667,1.232058,DecisionTreeRegressor()
8,Sepal.Width,Petal.Width,0.132858,regression,True,mean absolute error,0.644667,0.559017,DecisionTreeRegressor()
9,Sepal.Width,Species,0.156915,classification,True,weighted F1,0.353333,0.454805,DecisionTreeClassifier()
10,Petal.Length,Sepal.Length,0.525617,regression,True,mean absolute error,0.684667,0.324794,DecisionTreeRegressor()
11,Petal.Length,Sepal.Width,0.052136,regression,True,mean absolute error,0.330667,0.313427,DecisionTreeRegressor()
12,Petal.Length,Petal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
13,Petal.Length,Petal.Width,0.744945,regression,True,mean absolute error,0.644667,0.164425,DecisionTreeRegressor()
14,Petal.Length,Species,0.884812,classification,True,weighted F1,0.353333,0.925512,DecisionTreeClassifier()
15,Petal.Width,Sepal.Length,0.383911,regression,True,mean absolute error,0.684667,0.421816,DecisionTreeRegressor()
16,Petal.Width,Sepal.Width,0.254616,regression,True,mean absolute error,0.330667,0.246474,DecisionTreeRegressor()
17,Petal.Width,Petal.Length,0.798274,regression,True,mean absolute error,1.488667,0.300302,DecisionTreeRegressor()
18,Petal.Width,Petal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
19,Petal.Width,Species,0.927652,classification,True,weighted F1,0.353333,0.953215,DecisionTreeClassifier()
20,Species,Sepal.Length,0.409634,regression,True,mean absolute error,0.684667,0.404204,DecisionTreeRegressor()
21,Species,Sepal.Width,0.194307,regression,True,mean absolute error,0.330667,0.266416,DecisionTreeRegressor()
22,Species,Petal.Length,0.785393,regression,True,mean absolute error,1.488667,0.319479,DecisionTreeRegressor()
23,Species,Petal.Width,0.755749,regression,True,mean absolute error,0.644667,0.157460,DecisionTreeRegressor()
24,Species,Species,1.000000,predict_itself,True,None,0.000000,1.000000,None

In [106]:
# arranging the top ppsocres at top
sorted_df_ppscores = pps_matrix.sort_values(by = 'ppscore' , ascending = False)
sorted_df_ppscores

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,Sepal.Length,Sepal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
6,Sepal.Width,Sepal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
18,Petal.Width,Petal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
12,Petal.Length,Petal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
24,Species,Species,1.000000,predict_itself,True,None,0.000000,1.000000,None
19,Petal.Width,Species,0.927652,classification,True,weighted F1,0.353333,0.953215,DecisionTreeClassifier()
14,Petal.Length,Species,0.884812,classification,True,weighted F1,0.353333,0.925512,DecisionTreeClassifier()
17,Petal.Width,Petal.Length,0.798274,regression,True,mean absolute error,1.488667,0.300302,DecisionTreeRegressor()
22,Species,Petal.Length,0.785393,regression,True,mean absolute error,1.488667,0.319479,DecisionTreeRegressor()
23,Species,Petal.Width,0.755749,regression,True,mean absolute error,0.644667,0.157460,DecisionTreeRegressor()
13,Petal.Length,Petal.Width,0.744945,regression,True,mean absolute error,0.644667,0.164425,DecisionTreeRegressor()
2,Sepal.Length,Petal.Length,0.550423,regression,True,mean absolute error,1.488667,0.669271,DecisionTreeRegressor()
10,Petal.Length,Sepal.Length,0.525617,regression,True,mean absolute error,0.684667,0.324794,DecisionTreeRegressor()
4,Sepal.Length,Species,0.471649,classification,True,weighted F1,0.353333,0.658333,DecisionTreeClassifier()
3,Sepal.Length,Petal.Width,0.431739,regression,True,mean absolute error,0.644667,0.366339,DecisionTreeRegressor()
20,Species,Sepal.Length,0.409634,regression,True,mean absolute error,0.684667,0.404204,DecisionTreeRegressor()
15,Petal.Width,Sepal.Length,0.383911,regression,True,mean absolute error,0.684667,0.421816,DecisionTreeRegressor()
16,Petal.Width,Sepal.Width,0.254616,regression,True,mean absolute error,0.330667,0.246474,DecisionTreeRegressor()
21,Species,Sepal.Width,0.194307,regression,True,mean absolute error,0.330667,0.266416,DecisionTreeRegressor()
7,Sepal.Width,Petal.Length,0.172375,regression,True,mean absolute error,1.488667,1.232058,DecisionTreeRegressor()
9,Sepal.Width,Species,0.156915,classification,True,weighted F1,0.353333,0.454805,DecisionTreeClassifier()
8,Sepal.Width,Petal.Width,0.132858,regression,True,mean absolute error,0.644667,0.559017,DecisionTreeRegressor()
11,Petal.Length,Sepal.Width,0.052136,regression,True,mean absolute error,0.330667,0.313427,DecisionTreeRegressor()
5,Sepal.Width,Sepal.Length,0.006966,regression,True,mean absolute error,0.684667,0.679897,DecisionTreeRegressor()
1,Sepal.Length,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.364704,DecisionTreeRegressor()