In [1]:
print("hello")

hello

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
!pip install numpy

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.3.5)

In [5]:
import numpy as np

In [6]:
df = pd.read_csv('/Users/furkhanansari/Desktop/Data Science/DataSets/Salaries.csv')

In [7]:
# list of first five records
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [8]:
df.head(10)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [9]:
df.head(20)

         rank discipline  phd  service   sex  salary
0        Prof          B   56       49  Male  186960
1        Prof          A   12        6  Male   93000
2        Prof          A   23       20  Male  110515
3        Prof          A   40       31  Male  131205
4        Prof          B   20       18  Male  104800
5        Prof          A   20       20  Male  122400
6   AssocProf          A   20       17  Male   81285
7        Prof          A   18       18  Male  126300
8        Prof          A   29       19  Male   94350
9        Prof          A   51       51  Male   57800
10       Prof          B   39       33  Male  128250
11       Prof          B   23       23  Male  134778
12   AsstProf          B    1        0  Male   88000
13       Prof          B   35       33  Male  162200
14       Prof          B   25       19  Male  153750
15       Prof          B   17        3  Male  150480
16   AsstProf          B    8        3  Male   75044
17   AsstProf          B    4        0  Male   92000
18       Prof          A   19        7  Male  107300
19       Prof          A   29       27  Male  150500

In [12]:
df.head(50)

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960

In [ ]:
#attidubtes of Data frame
    #dtypes
    #columns
    #axes
    #ndim
    #size
    #shape
    #values

In [13]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [23]:
df['rank'].dtype

dtype('O')

In [25]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [26]:
df.axes

[RangeIndex(start=0, stop=78, step=1),
 Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')]

In [27]:
df.ndim

2

In [28]:
df.size

468

In [29]:
df.shape

(78, 6)

In [30]:
df.values

array([['Prof', 'B', 56, 49, 'Male', 186960],
       ['Prof', 'A', 12, 6, 'Male', 93000],
       ['Prof', 'A', 23, 20, 'Male', 110515],
       ['Prof', 'A', 40, 31, 'Male', 131205],
       ['Prof', 'B', 20, 18, 'Male', 104800],
       ['Prof', 'A', 20, 20, 'Male', 122400],
       ['AssocProf', 'A', 20, 17, 'Male', 81285],
       ['Prof', 'A', 18, 18, 'Male', 126300],
       ['Prof', 'A', 29, 19, 'Male', 94350],
       ['Prof', 'A', 51, 51, 'Male', 57800],
       ['Prof', 'B', 39, 33, 'Male', 128250],
       ['Prof', 'B', 23, 23, 'Male', 134778],
       ['AsstProf', 'B', 1, 0, 'Male', 88000],
       ['Prof', 'B', 35, 33, 'Male', 162200],
       ['Prof', 'B', 25, 19, 'Male', 153750],
       ['Prof', 'B', 17, 3, 'Male', 150480],
       ['AsstProf', 'B', 8, 3, 'Male', 75044],
       ['AsstProf', 'B', 4, 0, 'Male', 92000],
       ['Prof', 'A', 19, 7, 'Male', 107300],
       ['Prof', 'A', 29, 27, 'Male', 150500],
       ['AsstProf', 'B', 4, 4, 'Male', 92000],
       ['Prof', 'A', 33, 30, 'Male', 103106],
       ['AsstProf', 'A', 4, 2, 'Male', 73000],
       ['AsstProf', 'A', 2, 0, 'Male', 85000],
       ['Prof', 'A', 30, 23, 'Male', 91100],
       ['Prof', 'B', 35, 31, 'Male', 99418],
       ['Prof', 'A', 38, 19, 'Male', 148750],
       ['Prof', 'A', 45, 43, 'Male', 155865],
       ['AsstProf', 'B', 7, 2, 'Male', 91300],
       ['Prof', 'B', 21, 20, 'Male', 123683],
       ['AssocProf', 'B', 9, 7, 'Male', 107008],
       ['Prof', 'B', 22, 21, 'Male', 155750],
       ['Prof', 'A', 27, 19, 'Male', 103275],
       ['Prof', 'B', 18, 18, 'Male', 120000],
       ['AssocProf', 'B', 12, 8, 'Male', 119800],
       ['Prof', 'B', 28, 23, 'Male', 126933],
       ['Prof', 'B', 45, 45, 'Male', 146856],
       ['Prof', 'A', 20, 8, 'Male', 102000],
       ['AsstProf', 'B', 4, 3, 'Male', 91000],
       ['Prof', 'B', 18, 18, 'Female', 129000],
       ['Prof', 'A', 39, 36, 'Female', 137000],
       ['AssocProf', 'A', 13, 8, 'Female', 74830],
       ['AsstProf', 'B', 4, 2, 'Female', 80225],
       ['AsstProf', 'B', 5, 0, 'Female', 77000],
       ['Prof', 'B', 23, 19, 'Female', 151768],
       ['Prof', 'B', 25, 25, 'Female', 140096],
       ['AsstProf', 'B', 11, 3, 'Female', 74692],
       ['AssocProf', 'B', 11, 11, 'Female', 103613],
       ['Prof', 'B', 17, 17, 'Female', 111512],
       ['Prof', 'B', 17, 18, 'Female', 122960],
       ['AsstProf', 'B', 10, 5, 'Female', 97032],
       ['Prof', 'B', 20, 14, 'Female', 127512],
       ['Prof', 'A', 12, 0, 'Female', 105000],
       ['AsstProf', 'A', 5, 3, 'Female', 73500],
       ['AssocProf', 'A', 25, 22, 'Female', 62884],
       ['AsstProf', 'A', 2, 0, 'Female', 72500],
       ['AssocProf', 'A', 10, 8, 'Female', 77500],
       ['AsstProf', 'A', 3, 1, 'Female', 72500],
       ['Prof', 'B', 36, 26, 'Female', 144651],
       ['AssocProf', 'B', 12, 10, 'Female', 103994],
       ['AsstProf', 'B', 3, 3, 'Female', 92000],
       ['AssocProf', 'B', 13, 10, 'Female', 103750],
       ['AssocProf', 'B', 14, 7, 'Female', 109650],
       ['Prof', 'A', 29, 27, 'Female', 91000],
       ['AssocProf', 'A', 26, 24, 'Female', 73300],
       ['Prof', 'A', 36, 19, 'Female', 117555],
       ['AsstProf', 'A', 7, 6, 'Female', 63100],
       ['Prof', 'A', 17, 11, 'Female', 90450],
       ['AsstProf', 'A', 4, 2, 'Female', 77500],
       ['Prof', 'A', 28, 7, 'Female', 116450],
       ['AsstProf', 'A', 8, 3, 'Female', 78500],
       ['AssocProf', 'B', 12, 9, 'Female', 71065],
       ['Prof', 'B', 24, 15, 'Female', 161101],
       ['Prof', 'B', 18, 10, 'Female', 105450],
       ['AssocProf', 'B', 19, 6, 'Female', 104542],
       ['Prof', 'B', 17, 17, 'Female', 124312],
       ['Prof', 'A', 28, 14, 'Female', 109954],
       ['Prof', 'A', 23, 15, 'Female', 109646]], dtype=object)

In [39]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [46]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [43]:
df.shape[0]

78

In [44]:
df.shape[1]

6

In [47]:
#Data frame Methods
    #head
    #tail
    #describe
    #max
    #min
    #mean
    #median
    #std
    #sample
    #dropan

In [48]:
df.head(3)

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515

In [49]:
df.tail(3)

    rank discipline  phd  service     sex  salary
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646

In [51]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [52]:
df.max()

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [53]:
df.min()

rank          AssocProf
discipline            A
phd                   1
service               0
sex              Female
salary            57800
dtype: object

In [63]:
df.mean(numeric_only = True)

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [81]:
df.std(numeric_only = True)

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [65]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [79]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [92]:
df_50 = df.head(50)
df_50.mean(numeric_only = True)

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [90]:
df.head(50).mean(numeric_only =True)       #chaining of operations

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [95]:
df['phd'].head(5)             #method 1 of selecting col

0    56
1    12
2    23
3    40
4    20
Name: phd, dtype: int64

In [96]:
df.phd.head(5)                #method 2 of selecting col

0    56
1    12
2    23
3    40
4    20
Name: phd, dtype: int64

In [103]:
df[['phd']].tail(5)       # method 3 of selecting col this give data in dataframe format

    phd
73   18
74   19
75   17
76   28
77   23

In [104]:
df.phd.mean()

np.float64(19.705128205128204)

In [105]:
df.phd.median()

18.5

In [106]:
df.phd.mode()

0    4
Name: phd, dtype: int64

In [113]:
df[['phd']].describe()

             phd
count  78.000000
mean   19.705128
std    12.498425
min     1.000000
25%    10.250000
50%    18.500000
75%    27.750000
max    56.000000

In [110]:
df.phd.size

78

In [112]:
df.phd.count()

np.int64(78)

In [118]:
df_rank = df.groupby(['rank'])

In [120]:
df_rank.mean(numeric_only =True)

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [123]:
df.groupby('rank')[['salary']].mean()

                  salary
rank
AssocProf   91786.230769
AsstProf    81362.789474
Prof       123624.804348

In [128]:
df[df['salary'] < 120000]

         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
4        Prof          B   20       18    Male  104800
6   AssocProf          A   20       17    Male   81285
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
12   AsstProf          B    1        0    Male   88000
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
30  AssocProf          B    9        7    Male  107008
32       Prof          A   27       19    Male  103275
34  AssocProf          B   12        8    Male  119800
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
50   AsstProf          B   10        5  Female   97032
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [141]:
df[df['sex'] == 'Female'].count()

rank          39
discipline    39
phd           39
service       39
sex           39
salary        39
dtype: int64

In [143]:
df[['rank','salary']]

         rank  salary
0        Prof  186960
1        Prof   93000
2        Prof  110515
3        Prof  131205
4        Prof  104800
..        ...     ...
73       Prof  105450
74  AssocProf  104542
75       Prof  124312
76       Prof  109954
77       Prof  109646

[78 rows x 2 columns]

In [144]:
# Slicing the DataFrame wiht iloc(integer location)
    # df.iloc[0] --> firstrow
    # df.iloc[-1] --> lastrow
    # df.iloc[row,col]
    # df.[start:stop-1,start:start-1]
    # df.iloc[[0,5],[1,3]]   list of rows , list of col

In [145]:
df.iloc[0]

rank            Prof
discipline         B
phd               56
service           49
sex             Male
salary        186960
Name: 0, dtype: object

In [146]:
df.iloc[-1]

rank            Prof
discipline         A
phd               23
service           15
sex           Female
salary        109646
Name: 77, dtype: object

In [147]:
df.iloc[0:7]

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285

In [152]:
df.iloc[:,[-1]]

    salary
0   186960
1    93000
2   110515
3   131205
4   104800
..     ...
73  105450
74  104542
75  124312
76  109954
77  109646

[78 rows x 1 columns]

In [153]:
df.iloc[:,0:4]

         rank discipline  phd  service
0        Prof          B   56       49
1        Prof          A   12        6
2        Prof          A   23       20
3        Prof          A   40       31
4        Prof          B   20       18
..        ...        ...  ...      ...
73       Prof          B   18       10
74  AssocProf          B   19        6
75       Prof          B   17       17
76       Prof          A   28       14
77       Prof          A   23       15

[78 rows x 4 columns]

In [155]:
df.iloc[4:10,0:3]

        rank discipline  phd
4       Prof          B   20
5       Prof          A   20
6  AssocProf          A   20
7       Prof          A   18
8       Prof          A   29
9       Prof          A   51

In [156]:
df.iloc[[1,4,7,0],[3,4,1,0]]

   service   sex discipline  rank
1        6  Male          A  Prof
4       18  Male          B  Prof
7       18  Male          A  Prof
0       49  Male          B  Prof

In [157]:
df.iloc[0:11,0:4]

         rank discipline  phd  service
0        Prof          B   56       49
1        Prof          A   12        6
2        Prof          A   23       20
3        Prof          A   40       31
4        Prof          B   20       18
5        Prof          A   20       20
6   AssocProf          A   20       17
7        Prof          A   18       18
8        Prof          A   29       19
9        Prof          A   51       51
10       Prof          B   39       33

In [161]:
df.iloc[:,4:6]

       sex  salary
0     Male  186960
1     Male   93000
2     Male  110515
3     Male  131205
4     Male  104800
..     ...     ...
73  Female  105450
74  Female  104542
75  Female  124312
76  Female  109954
77  Female  109646

[78 rows x 2 columns]

In [170]:
df.iloc[[59]]

         rank discipline  phd  service     sex  salary
59  AssocProf          B   12       10  Female  103994

In [171]:
df.iloc[[0,2],]

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
2  Prof          A   23       20  Male  110515

In [172]:
# aggregate function
df[['phd','salary']].agg(['min','mean','max'])

            phd         salary
min    1.000000   57800.000000
mean  19.705128  108023.782051
max   56.000000  186960.000000

In [173]:
# basic discriptive statictics
    # df.describe
    # df.min
    # df.max
    # df.var
    # df.std
    # df.sem
    # df.skew
    # de.kurt

In [177]:
df['salary'].skew()

np.float64(0.45210256755588096)

In [180]:
df.phd.skew()

np.float64(0.6343660525514754)

In [181]:
df.phd.kurt()

np.float64(0.042503564567506036)